### ISSUE TITLE
week 01 作業回覆

### ISSUE THREAD

**Issue by azole** [MiaaaChen/git-practice#1]
整體作業正確。

如同昨天在課堂上的分享，從現在開始練習更深入地去探索一個技術，訓練自己去多問一點問題，有更多的好奇心一點。

觀察紀錄這邊，可以透過複製或截圖，確實地把看到的東西紀錄起來，可以參考課堂上分享的其他同學的成果，練習讓自己的報告更完整，這些將來都會是你累積的作品。

**Comment by MiaaaChen** [comment]
收到！我會練習多提問、深入研究新接觸到的技術，試著讓我的作業報告更完整！

**Comment by azole** [comment]
謝謝你的回覆，透過這門課來持續練習跟持續進步，等到學期末，一定會比現在強上許多，我們一起努力嚕。

如果沒有其他需要跟我討論的事，這個 issue 可以 close 了。
